name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Enable corepack and set npm version
      run: |
        corepack enable
        corepack prepare npm@10.9.0 --activate

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run typecheck

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm test

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Initialize CodeQL
      uses: github/codeql-action/init@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12
      with:
        languages: javascript-typescript

    - name: Autobuild
      uses: github/codeql-action/autobuild@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12

  fuzz:
    name: Fuzz Testing
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Enable corepack and set npm version
      run: |
        corepack enable
        corepack prepare npm@10.9.0 --activate

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Install fast-check for fuzzing
      run: |
        npm install fast-check@3.22.0 jest@29.7.0

    - name: Run fuzz tests
      run: |
        cat << 'EOF' > fuzz.test.mjs
        import fc from 'fast-check';
        import * as utils from './dist/utils.js';

        describe('Fuzz Testing', () => {
          test('detectPackageManager handles arbitrary strings', () => {
            fc.assert(fc.property(fc.string(), (input) => {
              try {
                const result = utils.detectPackageManager(input);
                expect(typeof result).toBe('string');
                expect(['npm', 'yarn', 'pnpm', 'bun'].includes(result)).toBe(true);
              } catch (error) {
                expect(error).toBeInstanceOf(Error);
              }
            }));
          });

          test('validateTemplateVariables handles arbitrary objects', () => {
            fc.assert(fc.property(fc.object(), (input) => {
              try {
                const result = utils.validateTemplateVariables(input, []);
                expect(typeof result).toBe('object');
              } catch (error) {
                expect(error).toBeInstanceOf(Error);
              }
            }));
          });

          test('renderTemplate handles arbitrary template strings', () => {
            fc.assert(fc.property(fc.string(), fc.object(), (template, vars) => {
              try {
                const result = utils.renderTemplate(template, vars);
                expect(typeof result).toBe('string');
              } catch (error) {
                expect(error).toBeInstanceOf(Error);
              }
            }));
          });
        });
        EOF
        
        cat << 'EOF' > jest.config.js
        export default {
          extensionsToTreatAsEsm: ['.mjs'],
          transform: {},
          testMatch: ['**/*.test.mjs'],
          testTimeout: 30000,
          testEnvironment: 'node'
        };
        EOF
        
        npx jest fuzz.test.mjs